### ISSUE TITLE
[Bug]: 64 bit memory outputs 1 for all bits

### ISSUE THREAD

**Issue by EnderShadow** [Turing-Complete-Game/Suggestions-and-Issues#37]
### What happened?

When using a minimal setup to write to memory and then read from memory, 2^64-1 is returned as the value even though that's not what was written.
![image](https://user-images.githubusercontent.com/3260768/141437191-1220539e-5448-4655-a126-76c56a806bf8.png)

Also, just placing a 64 bit memory component and ticking the game causes the same issue

### Version

Development

### Operating System

Arch Linux

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
I can still reproduce this on the most recent versions. It's probably caused by the RAM loading the special address `-1`, which has the special value `-1` which then get's output. This happens when you neither write nor read on last two ticks.

**Comment by EnderShadow** [comment]
But is still reproduceable

**Comment by Stuffe** [comment]
I think it is fixed now

**Comment by MegaIng** [comment]
This either wasn't fully fixed or has resurfaced: https://discord.com/channels/828292123936948244/897062022099918871/925187662170701865

**Comment by Stuffe** [comment]
actually fixed this time
