### ISSUE TITLE
[Bug]: 32/64 bit values display differently, counters don't follow current format, wire value display inconsistent, I/O display inconsistent

### ISSUE THREAD

**Issue by Cereal4Dinner** [Turing-Complete-Game/Suggestions-and-Issues#431]
### What happened?

A bug happened!

The 32 bit and 64 bit values show up differently on the component, wire, lower bar area and the I/O area. The msb for the wire is on top, component on bottom, the lower bar shows both (pictured component has it on top and opposite for setting bits), and the I/O area is shows partial text for input and a bit for output. Seems the msb should be on top. (PS The scroll on 32 bit input and output pins is just weirdly inconsistent, smaller font or 2 lines would be better). Also the unbuffered output components don't show anything.

The 64 bit counter always shows signed, and the byte, 16 and 32 bit counters always show unsigned, instead of cycling thru formats.

Only for wires going up/down do the values print perpendicular. Left/right wires print along the wire. Angled wires print along the wire unless the wire starts up/down, then it stays perpendicular I suggest all values print along the wire. 
Also for the wires, only 64 bit starts and stops printing according to the width of the number, imo looks better, while the others print from pin to pin, sticking out past the end of the wire. And if you keep the perpendicular printing, 64 bit still starts and stops according to width instead of height.

The I/O display is in need of love.
Input: only bit and byte inputs are configurable. 16, 32, 64 bit inputs only show numbers, partial for large or hex numbers.
Memory: only byte counters and registers.
Output: only regular bit and byte show correctly (including unbuffered, at least for output), 16, 32, 64 bit outputs show a red bit. 

Sorry so much is here, it started out with me trying to set a 64 bit constant, and just kept seeing things.

![20220507171301_1](https://user-images.githubusercontent.com/64340180/167276492-3ec9a860-94b6-421f-ab07-0d6ef5d2ea3e.jpg)
![20220507172737_1](https://user-images.githubusercontent.com/64340180/167276598-fc63988d-6af8-425f-aa92-7f3f9d8be9f2.jpg)
Actually the regular bit output in the 2nd screenshot is still red, but I've seen it working properly elsewhere, so more confusion.

### Version

Latest

### Operating System

win11pro

### Code of Conduct

- [X] I agree to follow this project's Code of Conduct

**Comment by Stuffe** [comment]
Thank you for going through this mess. I am uploading a patch to it now, but feel free to check again with this schematic and let me know if there are more issues.

**Comment by Cereal4Dinner** [comment]
I looked at the number display for all 3 number formats. Most of the other stuff was more suggestions, qol. except the i/o area, that can use help, and i hope it will eventually get done. But fixing numbers will definitely prevent headaches for users.

16 and 8 counters only displays unsigned

32b tristate output displays only 1. its hex is single line where other 32b i/o is 2 lines.

on the lower bar, constants display a mini selfie, but inputs show a number and the hex format has the halves swapped for 64, 32

64, 32b: the delay lines are the only components that display hex msb first,; the wires, constants, registers, counters, i/o all have the lower half on top, including the bit setting on the lower bar


First the 3 different formats showing 0x80008081 on constants, registers, ..., if I missed any let me know

![20220511232440_1](https://user-images.githubusercontent.com/64340180/168010576-c308909d-8362-439a-b510-359b3319ce06.jpg)

![20220511232455_1](https://user-images.githubusercontent.com/64340180/168010600-ceaf505b-455a-4a1e-b142-bc954e0ded09.jpg)

![20220511232507_1](https://user-images.githubusercontent.com/64340180/168010630-385f741b-5508-4f9e-b959-2eb1725188ea.jpg)

The swapped halves, also shows the 32b tristate does have the correct value while displaying 1

![20220511232815_1](https://user-images.githubusercontent.com/64340180/168010656-dd8f6a40-5339-492d-8529-572c77b0c2c3.jpg)

This shows the swapped halves and also the lower half on top bit settings

![20220511232420_1](https://user-images.githubusercontent.com/64340180/168010675-2ef136a9-d78b-4f79-b5ed-9979dba640e8.jpg)

**Comment by Cereal4Dinner** [comment]
Forgot about the 8 bit i/o and all 1 bit

The byte tristate always shows 1 like the 32bit.
The bit tristate always shows off.
![20220514081913_1](https://user-images.githubusercontent.com/64340180/168436578-3a076af1-a23b-40a8-aefa-e11aaa4f601f.jpg)
![20220514081908_1](https://user-images.githubusercontent.com/64340180/168436587-1a3d6b07-d409-457c-8e69-a4dc5687afbd.jpg)

**Comment by Cereal4Dinner** [comment]
I'm not sure this is going to anyone. Do I need to open a new bug report?

**Comment by Stuffe** [comment]
Thanks again, this was very helpful. I have fixed these things and they will be live in patch 0.760, so feel free to test again :)

One thing though is that the lower bars being visually different in terms of how they show the numbers is not a priority right now, but the bugs should be fixed.

**Comment by Cereal4Dinner** [comment]
One item got missed. the bit tristate still shows only off.

I am a bit surprised that, with the hex display of 32 and 64 bit, you have the more significant half on the bottom, but I'm no expert and only thought it might be easier to read left to right, top to bottom. It's your game, and as long as you're consistent and I know about it, it's ok.
