### ISSUE TITLE
[Bug]: SIGNED LESS output evaluation not correct

### ISSUE THREAD

**Issue by FRALEXAlexander** [Turing-Complete-Game/Suggestions-and-Issues#69]
### What happened?

Is 38 less than 141 shoud be true but if I run the ticks it stops at this point.

![image](https://user-images.githubusercontent.com/24719636/142423845-1af10a7b-ab9d-4637-bdac-d416b5f848fa.png)

### Version

Latest

### Operating System

Windows 10

### Code of Conduct

- [x] I agree to follow this project's Code of Conduct

**Comment by MegaIng** [comment]
This is signed less, so 38 is bigger than 141, since 141 is -115 and 38>-115

**Comment by altrag** [comment]
I don't know if the text is "wrong" since its following the user's display choice.. but definitely is misleading if you aren't thinking in signed 8-bit terms!
Perhaps a "Hint:  Did you try changing the 255/-1 button?" added on if its not already set to -1 mode.

**Comment by MegaIng** [comment]
>  since its following the user's display choice..

No it's not. The input has the correct negative value.

**Comment by altrag** [comment]
> No it's not. The input has the correct negative value.
Woops so it is.

**Comment by Stuffe** [comment]
fixed next update

**Comment by altrag** [comment]
![image](https://user-images.githubusercontent.com/59858259/142740679-b7ec632b-3034-493d-95a2-283dcfc78309.png)

Second value seems to be correct now (0.314 Beta), first one still shows unsigned numbers.
